version: '3.8'

services:
  consul:
    image: consul:1.15
    ports:
      - "8500:8500"
    command: ["agent", "-dev", "-client=0.0.0.0"]

  auth:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.auth
    ports:
      - "50051:50051"
    depends_on:
      - consul

  catalog:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.catalog
    ports:
      - "50052:50052"
    depends_on: 
      - consul

  order:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.order
    ports:
      - "50053:50053"
    depends_on: 
      - consul
      - auth
      - catalog
  
  payment:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.payment
    ports:
      - "50054:50054"
    depends_on: 
      - consul
      - order
      - rabbitmq

  gateway:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.gateway
    ports:
      - "8080:8080"
    depends_on:
      - auth
      - catalog
      - order

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - gateway
  
  graphql-gateway:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.graphql_gateway
    ports:
      - "8000:8000"
    depends_on:
      - auth
      - catalog
      - order
    
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"   # AMQP порт
      - "15672:15672" # Web UI порт
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    depends_on:
      - order
  
  notification:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.notification
    ports:
      - "50055:50055"
    depends_on:
      - order
      - gateway